//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingWallpaper {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BingWallpaper.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bing WallPaper 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Update 的本地化字符串。
        /// </summary>
        internal static string ForceUpdate {
            get {
                return ResourceManager.GetString("ForceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change in Interval 的本地化字符串。
        /// </summary>
        internal static string IntervalChange {
            get {
                return ResourceManager.GetString("IntervalChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch on Startup 的本地化字符串。
        /// </summary>
        internal static string LaunchOnStartup {
            get {
                return ResourceManager.GetString("LaunchOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random wallpaper 的本地化字符串。
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Wallpaper 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save current wallpaper 的本地化字符串。
        /// </summary>
        internal static string SaveDialgName {
            get {
                return ResourceManager.GetString("SaveDialgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Desktop Widget 的本地化字符串。
        /// </summary>
        internal static string ShowWidget {
            get {
                return ResourceManager.GetString("ShowWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Local Wallpaper DB 的本地化字符串。
        /// </summary>
        internal static string UpdateDB {
            get {
                return ResourceManager.GetString("UpdateDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WallPaper Story 的本地化字符串。
        /// </summary>
        internal static string WallPaperStory {
            get {
                return ResourceManager.GetString("WallPaperStory", resourceCulture);
            }
        }
    }
}
